# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bf3db601e3d24686ad44fd95df1dab2"
name = "shopping-cart-coordinadora-app"
handle = "shopping-cart-coordinadora-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "btbintegro.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
